[package]
name = "igor-tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "igor_tree"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.0"
regex = "1.10.4"
